// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChartController from "./chart_controller"
application.register("chart", ChartController)

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PasswordVisibilityController from "./password_visibility_controller"
application.register("password-visibility", PasswordVisibilityController)

import PresenceController from "./presence_controller"
application.register("presence", PresenceController)

import QuestionnaireController from "./questionnaire_controller"
application.register("questionnaire", QuestionnaireController)

import SystemMonitorController from "./system_monitor_controller"
application.register("system-monitor", SystemMonitorController)
