# config/deploy.yml
service: consilium
image: luisomarrojasmercado/consilium

builder:
  arch: amd64

servers:
  # 1. El Servidor Web
  web:
    hosts:
      - 74.208.227.22
    # --- AQUÍ ESTÁ EL ARREGLO ---
    # Damos 100 segundos de paciencia (20 intentos x 5s)
    # para que la migración pesada de Solid Queue termine sin cortar el deploy.
    healthcheck:
      path: /up
      port: 3000
      max_attempts: 20
      interval: 5s
    env:
      clear:
        SOLID_QUEUE_IN_PUMA: "false"

  # 2. El Servidor de Tareas (Workers)
  job:
    hosts:
      - 74.208.227.22
    # Usamos bin/rails que es más nativo para Rails 8
    cmd: bin/rails solid_queue:start
    env:
      clear:
        SOLID_QUEUE_IN_PUMA: "false"

registry:
  username: luisomarrojasmercado
  password: <%= ENV["KAMAL_REGISTRY_PASSWORD"] %>

env:
  secret:
    - RAILS_MASTER_KEY
    - MYSQL_ROOT_PASSWORD
  clear:
    DB_HOST: 74.208.227.22
    # Tu llave secreta actual
    SECRET_KEY_BASE: eb6b0d8459c79fd2e1f47dee27e70d22ff49989dc27d28fad0bf7876fe283d87481066101cf8406f85ebebc4c44083a3f5a9ecb50afaa1cb5761aa1e739accbc
    REDIS_URL: "redis://74.208.227.22:6379/1"
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
    SOLID_QUEUE_IN_PUMA: "false"

accessories:
  db:
    image: mysql:8.0
    host: 74.208.227.22
    port: 3306
    env:
      clear:
        MYSQL_ROOT_PASSWORD: '<%= ENV["MYSQL_ROOT_PASSWORD"] %>'
        MYSQL_DATABASE: consilium_production
      secret:
        - MYSQL_ROOT_PASSWORD
    files:
      - config/mysql/production.cnf:/etc/mysql/conf.d/production.cnf
    directories:
      - data:/var/lib/mysql

  redis:
    image: redis:7.0
    host: 74.208.227.22
    port: 6379
    directories:
      - data:/data