# Nombre de tu aplicación
service: consilium

# Tu imagen en Docker Hub
image: luisomarrojasmercado/consilium

builder:
  arch: amd64

# Agregamos la sección proxy explícita para configurar el tiempo, 
# pero forzamos SSL falso y usamos la IP como host.
proxy:
  ssl: false
  host: 74.208.227.22
  healthcheck:
    path: /up
    interval: 20  # Revisa cada 20 segundos (da más tiempo para migraciones)
    timeout: 5

# Servidores donde se desplegará
servers:
  # 1. El Servidor Web
  web:
    hosts:
      - 74.208.227.22
    env:
      clear:
        SOLID_QUEUE_IN_PUMA: "false"

  # 2. El Servidor de Tareas
  job:
    hosts:
      - 74.208.227.22
    cmd: bundle exec rails solid_queue:start
    proxy: false
    env:
      clear:
        SOLID_QUEUE_IN_PUMA: "false"
        SOLID_QUEUE_QUEUES: "*"
        SOLID_QUEUE_PROCESSES: "worker,scheduler"

# Credenciales
registry:
  username: luisomarrojasmercado
  password:
    - KAMAL_REGISTRY_PASSWORD

# Variables de entorno
env:
  secret:
    - RAILS_MASTER_KEY
    - MYSQL_ROOT_PASSWORD
    - SECRET_KEY_BASE
    - SMTP_ADDRESS
    - SMTP_PORT
    - SMTP_USERNAME
    - SMTP_PASSWORD
    - SMTP_DOMAIN
    - MAILER_SENDER
    - OPENAI_ACCESS_TOKEN
  clear:
    DB_HOST: 74.208.227.22
    REDIS_URL: "redis://74.208.227.22:6379/1"
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
    SOLID_QUEUE_IN_PUMA: "false"

# Accesorios
accessories:
  db:
    image: mysql:8.0
    host: 74.208.227.22
    port: 3306
    env:
      clear:
        MYSQL_DATABASE: consilium_production
      secret:
        - MYSQL_ROOT_PASSWORD
    files:
      - config/mysql/production.cnf:/etc/mysql/conf.d/production.cnf
    directories:
      - data:/var/lib/mysql

  netdata:
    image: netdata/netdata
    host: 74.208.227.22
    port: 19999
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env:
      clear:
        NETDATA_CHECKPOINT_INCLUDED_CONFIGS: "true"
        NETDATA_CLOUD_SETTING: "disabled"
        NETDATA_REGISTRY_ENABLED: "no"
        NETDATA_DISABLE_CLOUD: "1"

  redis:
    image: redis:7.0
    host: 74.208.227.22
    port: 6379
    directories:
      - data:/data

volumes:
  - "/var/lib/consilium/storage:/rails/storage"
  - "log:/rails/log"